runtime: nodejs20
service: api  # <-- VERY IMPORTANT!.gitignore
instance_class: F1  # lowest-cost instance for learning/testing
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
