apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend
  labels:
    app: my-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-backend
  template:
    metadata:
      labels:
        app: my-backend
    spec:
      containers:
        - name: my-backend
          image: <+artifact.image>    # Harness will inject the built image here
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
spec:
  selector:
    app: my-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
